#!/usr/bin/env python3
"""Extracts the melodies Scales plays from public MIDI files into src/tunes.ts.

Only the notes of public-domain compositions are taken; the MIDI files themselves are
not part of the repo. Usage: python3 tools/midi2ts.py <dir with the .mid files>

  crab.mid   https://www.flutetunes.com/tunes/bach-musical-offering-crab-canon.mid
  cairo.mid  https://www.flutetunes.com/tunes/the-streets-of-cairo.mid
  bolero.mid https://bitmidi.com/uploads/18945.mid  (sequenced by David Weatherford)
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from midi import parse

src = sys.argv[1]

def notes(file, track, start=0, end=None, unit=1, shift=0):
    """[onset, midi, length] in units, relative to `start`."""
    _, tracks = parse(os.path.join(src, file))
    out = []
    for s, m, d, _v, _ch in tracks[track][1]:
        if s < start or (end is not None and s >= end):
            continue
        out.append((round((s - start) / unit), m + shift, max(1, round(d / unit))))
    return out

def flat(ns):
    return ', '.join(f'{a}, {b}, {c}' for a, b, c in ns)

# Bolero: 192 ticks per beat, 3/4. Unit = 1/12 beat (16 ticks), 36 per bar.
# Each theme is a 16-bar solo in an 18-bar window; the last 2 bars are ostinato only.
BAR = 576
flute_a = notes('bolero.mid', 1, 2880, 2880 + 16 * BAR, 16)
bassoon_b = notes('bolero.mid', 12, 23616, 23616 + 16 * BAR, 16, shift=12)
ostinato = notes('bolero.mid', 26, BAR, 3 * BAR, 16)
snare = notes('bolero.mid', 23, 1728, 1728 + 2 * BAR, 16)

# Crab canon: 384 ticks per beat, 2/2. Unit = eighth note (192 ticks). Voice 2 is voice 1 reversed.
crab = notes('crab.mid', 1, 0, None, 192)
# Streets of Cairo: 384 ticks per beat, 4/4, first note at tick 1152. Unit = sixteenth (96 ticks).
cairo = notes('cairo.mid', 1, 1152, None, 96)

out = f'''// Generated by tools/midi2ts.py - do not edit by hand.
// Notes as flat [onset, midi, length] triples, in each tune's time unit.

/** Ravel, Bolero: theme A (flute), in C. Unit: 1/12 beat, 36 per 3/4 bar. */
export const BOLERO_A = [{flat(flute_a)}];
/** Ravel, Bolero: theme B (bassoon, up an octave). */
export const BOLERO_B = [{flat(bassoon_b)}];
/** The pizzicato ostinato, two bars. */
export const BOLERO_OSTINATO = [{flat(ostinato)}];
/** The snare, two bars. */
export const BOLERO_SNARE = [{flat(snare)}];

/** Bach, Musical Offering: Canon a 2 cancrizans, first voice, in G minor. Unit: eighth note. */
export const CRAB = [{flat(crab)}];

/** Thornton, The Streets of Cairo (the snake charmer song), in E minor. Unit: sixteenth note. */
export const CAIRO = [{flat(cairo)}];
'''
open(os.path.join(os.path.dirname(__file__), '..', 'src', 'tunes.ts'), 'w').write(out)
for name, ns in [('A', flute_a), ('B', bassoon_b), ('ost', ostinato), ('snare', snare), ('crab', crab), ('cairo', cairo)]:
    print(name, len(ns), 'end', max(a + c for a, _, c in ns))
